name: Generate OTA JSON for LineageOS

on:
  push:  # Runs on every commit
    branches:
      - main  # Modify if needed
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-ota-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Fetch the latest release tag from GitHub API
      - name: Get latest release info
        id: latest_release
        run: |
          echo "=============================================="
          echo "🔍 FETCHING LATEST RELEASE FROM GITHUB API..."
          echo "=============================================="

          API_URL="https://api.github.com/repos/${{ github.repository }}/releases/latest"
          echo "📡 API Request URL: $API_URL"

          RESPONSE=$(curl -s $API_URL)

          if [[ -z "$RESPONSE" ]]; then
            echo "❌ ERROR: Failed to fetch release data. Exiting."
            exit 1
          fi

          echo "✅ SUCCESS: Fetched release data."
          echo "📜 RAW API RESPONSE:"
          echo "$RESPONSE" | jq

          # Extract release tag
          RELEASE_TAG=$(echo "$RESPONSE" | jq -r .tag_name)
          if [[ -z "$RELEASE_TAG" || "$RELEASE_TAG" == "null" ]]; then
            echo "❌ ERROR: Could not fetch latest release tag. Exiting."
            exit 1
          fi
          echo "📌 RELEASE TAG FOUND: $RELEASE_TAG"
          echo "TAG_NAME=$RELEASE_TAG" >> $GITHUB_ENV

          # Extract OTA file details
          echo "🔎 Searching for OTA ZIP file in release assets..."
          ASSET_URL=$(echo "$RESPONSE" | jq -r '.assets[] | select(.name | endswith(".zip")) | .browser_download_url')
          FILE_NAME=$(basename "$ASSET_URL")

          if [[ -z "$ASSET_URL" || "$ASSET_URL" == "null" ]]; then
            echo "❌ ERROR: Could not find a valid OTA zip file in assets. Exiting."
            exit 1
          fi

          echo "📂 OTA ZIP FILE FOUND: $FILE_NAME"
          echo "🌍 OTA FILE URL: $ASSET_URL"

          echo "ASSET_URL=$ASSET_URL" >> $GITHUB_ENV
          echo "FILENAME=$FILE_NAME" >> $GITHUB_ENV

          # Extract file size
          SIZE=$(echo "$RESPONSE" | jq -r '.assets[] | select(.name | endswith(".zip")) | .size')
          echo "📏 FILE SIZE: $SIZE bytes"
          echo "SIZE=$SIZE" >> $GITHUB_ENV

          # Extract version from tag name
          echo "🔍 Extracting Android version from release tag..."
          VERSION=$(echo "$RELEASE_TAG" | grep -oP 'lineage-\K[0-9]+(\.[0-9]+)?')

          if [[ -z "$VERSION" ]]; then
            echo "❌ ERROR: Could not determine version from tag ($RELEASE_TAG). Exiting."
            exit 1
          fi

          echo "✅ ANDROID VERSION FOUND: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Step 3: Generate OTA JSON
      - name: Generate OTA JSON
        run: |
          echo "=============================================="
          echo "📦 GENERATING OTA JSON FILE..."
          echo "=============================================="

          OTA_JSON="ota.json"

          echo "🔍 Calculating MD5 checksum for verification..."
          MD5=$(curl -sL "${{ env.ASSET_URL }}" | md5sum | awk '{print $1}')
          echo "🔑 MD5 CHECKSUM: $MD5"

          echo "⏳ Generating timestamp..."
          TIMESTAMP=$(date +%s)
          echo "📅 TIMESTAMP: $TIMESTAMP"

          echo "✍️ Writing OTA JSON file..."
          cat <<EOF > $OTA_JSON
          {
            "response": [
              {
                "datetime": $TIMESTAMP,
                "filename": "${{ env.FILENAME }}",
                "id": "$MD5",
                "romtype": "UNOFFICIAL",
                "size": ${{ env.SIZE }},
                "url": "${{ env.ASSET_URL }}",
                "version": "${{ env.VERSION }}"
              }
            ]
          }
          EOF

          echo "✅ SUCCESS: OTA JSON File Created!"
          cat ota.json | jq

      # Step 4: Upload the OTA JSON file as an artifact
      - name: Upload OTA JSON
        uses: actions/upload-artifact@v4
        with:
          name: ota-json
          path: ota.json

      # Step 5: Commit and push OTA JSON to repository
      - name: Commit and push OTA JSON
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: |
          echo "=============================================="
          echo "🚀 COMMITTING & PUSHING OTA JSON TO REPO..."
          echo "=============================================="

          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          echo "📂 Staging ota.json for commit..."
          git add ota.json
          
          echo "✍️ Creating commit..."
          git commit -m "Add OTA JSON for latest release ${{ env.TAG_NAME }}"

          echo "📤 Pushing commit to repository..."
          git push origin HEAD:${{ github.ref_name }}

          echo "✅ SUCCESS: OTA JSON pushed to repository!"
